export const LEGACY_POOL = [
  { id: "senior-contact", title: "校友的联系方式", description: "初始 Network +8", initialEffects: { network: 8 } },
  { id: "readable-resume", title: "终于能看的简历", description: "初始 Profile +10", initialEffects: { profile: 10 } },
  { id: "rejection-calm", title: "被拒绝十次以后产生的奇怪平静", description: "初始 Confidence +8", initialEffects: { confidence: 8 } },
  { id: "coffee-chat", title: "Coffee Chat 经验", description: "Networking 成功率 +4%", modifiers: { networkingProbability: 0.04 } },
  { id: "interview-notes", title: "超详细的面经", description: "Interview 成功率 +4%", modifiers: { interviewProbability: 0.04 } },
  { id: "portfolio-made", title: "第一个作品集", description: "作品集事件少消耗 2 Energy", modifiers: { portfolioEnergyDiscount: 2 } },
  { id: "jd-reader", title: "我知道 JD 在写什么了", description: "研究岗位时额外 Profile +2", modifiers: { researchProfileBonus: 2 } },
  { id: "boundaries", title: "边界感", description: "初始 Energy +5", initialEffects: { energy: 5 } },
  { id: "airport-regular", title: "机场熟客", description: "旅行路线事件抽取权重 ×1.30", modifiers: { travelWeight: 1.3 } },
  { id: "first-client", title: "第一位客户", description: "Freelancer 路线事件抽取权重 ×1.30", modifiers: { freelanceWeight: 1.3 } },
  { id: "first-user", title: "第一个用户", description: "创业路线事件抽取权重 ×1.30", modifiers: { startupWeight: 1.3 } },
  { id: "stall-pass", title: "摊主体验卡", description: "摆摊／小生意路线事件抽取权重 ×1.30", modifiers: { stallWeight: 1.3 } },
  { id: "professor-meeting", title: "教授的 Meeting 邀请", description: "Academic 路线事件抽取权重 ×1.30", modifiers: { academicWeight: 1.3 } },
  { id: "comfortable-pillow", title: "超级舒服的枕头", description: "第一次进入 Final Round 时 Energy +4，且该轮成功率 +4%", modifiers: { finalRoundEnergy: 4, finalRoundProbability: 0.04 } },
  { id: "power-bank", title: "大容量充电宝", description: "Energy 第一次降到 20 或以下时自动恢复 7 点", modifiers: { lowEnergyThreshold: 20, lowEnergyRecovery: 7 } },
  { id: "campus-celebrity", title: "校园红人", description: "开局 20% 概率获得 Networking Opportunity；否则 Network +2", modifiers: { networkingOpportunityChance: 0.2, networkingFallback: 2 } },
  { id: "seven-shot-americano", title: "七倍浓缩美式", description: "开局 Energy +15；每个事件后有 25% 概率额外消耗 3 Energy", initialEffects: { energy: 15 }, modifiers: { postEventEnergyDrainChance: 0.25, postEventEnergyDrain: 3 } },
  { id: "interview-review", title: "面试复盘", description: "第一次面试失败后 Profile +3，下一次面试成功率 +5%", modifiers: { interviewFailureProfile: 3, nextInterviewProbability: 0.05 } },
  { id: "application-amnesia", title: "“我真的投过这家公司吗？”", description: "Application 事件有 12% 概率额外获得 1 次申请，每局最多 2 次", modifiers: { bonusApplicationChance: 0.12, maxBonusApplications: 2 } },
  { id: "interviewer-approval", title: "面试官欣赏的眼神", description: "第一次 Behavioral 或 Case Interview 成功率 +5%", modifiers: { authenticInterviewProbability: 0.05 } },
  { id: "extrovert-mask", title: "E人面具", description: "Group Interview 成功率 +7%", modifiers: { groupInterviewProbability: 0.07 } },
];

export const LEGACY_BY_ID = new Map(LEGACY_POOL.map((legacy) => [legacy.id, legacy]));
